version: "3.8"

services:
  jupyter:
    build:
      dockerfile: Dockerfile
    image: fastai-local-v2
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: 2g
    volumes:
      - fastai-notebooks:/home/jupyter
    restart: unless-stopped

volumes:
  fastai-notebooks:
    name: fastai-notebooks
